export const DEFAULT_SKILL_SUGGESTIONS = [
  "Python",
  "SQL",
  "Machine Learning",
  "Deep Learning",
  "NLP",
  "Computer Vision",
  "MLOps",
  "FastAPI",
  "Django",
  "Flask",
  "PostgreSQL",
  "MongoDB",
  "AWS",
  "Azure",
  "GCP",
  "Docker",
  "Kubernetes",
  "PyTorch",
  "TensorFlow",
  "Scikit-learn",
  "Spark",
  "Airflow",
  "React",
  "TypeScript",
  "Node.js",
  "B2B SaaS",
  "Roadmap",
  "Analytics",
  "Experimentation",
  "Vector DB",
  "LangChain",
  "RAG",
];

export const EMPTY_CAMPAIGN_FORM = {
  campaignName: "",
  location: "",
  positionName: "",
  desiredSkillsText: "",
  experience: "3-5",
  sampleCvFile: null,
  targetProfiles: 25,
  status: "Active",
};